### ISSUE TITLE
spec_correction_together.py code seems wrong.

### ISSUE THREAD

**Issue by yangdongchao** [MihawkHu/DCASE2020_task1#10]
`for group, x in zip(waves30, ['b', 'c', 's1','s2','s3']):
    i = 0
    for sc in group:
        wav_a = 'audio/' + sc + 'a.wav'
        wav_x = 'audio/' + sc + x + '.wav'
        stereo_a, fs = sound.read(file_path + wav_a, stop=duration * sr)
        stereo_x, fs = sound.read(file_path + wav_x, stop=duration * sr)
        # compute STFT of the paired signals
        STFT_a = librosa.stft(stereo_a, n_fft=num_fft, hop_length=hop_length)
        STFT_x = librosa.stft(stereo_x, n_fft=num_fft, hop_length=hop_length)
        # compute average value per each bin
        STFT_ref = np.abs(STFT_x)
        STFT_corr_coeff = STFT_ref/np.abs(STFT_a)
        # stack averaged values
        STFT_all[i,:,:] = STFT_corr_coeff
        i=i+1`

when you calculate the STFT_corr_coeff, the range of variable i is [0,150], but your STFT_corr_coeff  shape is [750, :, :].
so I guess you place the wrong position for variable i.

**Comment by MihawkHu** [comment]
Hi, thanks for your interests. 

For your question, that's not a mistake. For the approach 'spectrum correction', some STFT features from the reference device (we used device A) are calcuted the mean value to serve as the STFT_corr_coeff. 750 is the total number of the audio clips that can be used. According to the original paper who proposed this approach, it's no need to average all the audio clips. Only 50 audio clips are enough to get a relatively accurate coefficient. In our work, we used 150 audio clips to get the coefficient.
