### ISSUE TITLE
About the ensemble.

### ISSUE THREAD

**Issue by jiminbot20** [MihawkHu/DCASE2020_task1#13]
Can I understand this code **eval_fusion_vote_10class.py**(https://github.com/MihawkHu/DCASE2020_task1/blob/2384da9d357bc6be9648701a0ae0c4b4be285e36/task1a/10class/eval_fusion_vote_10class.py)
as an ensemble code?

**Comment by MihawkHu** [comment]
Yes it's to evaluate the ensembled system of 3 models.
