### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by debottam-dutta7** [MihawkHu/DCASE2020_task1#14]
Hi, very interesting work! Currently, I am trying to reproduce to the task1a FCNN results where you reported 76.9 % accuracy with all the augmentations. I am a bit confused about the evaluation_setup files. 

1. I see that fold1_train_all.csv has 69825 files and trainall_full.csv has 100345 files. Which one of these two should be used for training to reproduce the results (76.9% model) along with spectrum correction and reverb+drc  augmentation? 
2. Could you tell me which one of the three rir_label i.e 2003, mardy and reverb, was used in your ICASSP paper for reverb+drc augmentation? Was energy normalization used?

I appreciate your help in clarifying the confusion.

**Comment by MihawkHu** [comment]
Hi, 

Thanks for your interests! For your questions:

1 We used all the data augmentation techniques that mentioned in our report to get the final system. We realized that the current csv files look a bit confusing, and we just made some modifications to clean the codes and make it easier to understand. You can refer to the current fold1_train_all.csv file (https://github.com/MihawkHu/DCASE2020_task1/blob/master/task1a/10class/evaluation_setup/fold1_train_all.csv). It indicates all data we used to train the 10-class model. Specifically, we have Original data + Mix audios + Random noise + Pitch shift + Speed change + Spectrum correction + Reverberation with dynamic range compression (mardy + reverb + 2003). For the 3-class model, you can refer to the csv file of https://github.com/MihawkHu/DCASE2020_task1/blob/master/task1a/3class/evaluation_setup/fold1_train_all_3class.csv. 

2 We used all the three types of reverberation data (RIR from mardy, reverb and 2003). As pointed in the fold1_train_all.csv file, we used 3 types of reverberation data, as each device A audio has 3 different reverberation transformations. You can check https://github.com/MihawkHu/DCASE2020_task1/tree/master/task1a/data_augmentation/spectrum_correction for more details about how to generating them. Energy nomalization is used.

**Comment by debottam-dutta7** [comment]
Thanks. 
I assume you have used .m scripts in reverb_drc/m-scripts/ instead of _en.m scripts ( as given in [gen_RevDevelopment.sh](https://github.com/MihawkHu/DCASE2020_task1/blob/master/task1a/data_augmentation/reverb_drc/gen_RevDevelopment.sh)). Did you observe any difference in results with energy normalization in reverb augmentation? I am just curious since these results are not mentioned in the report or the paper.

**Comment by MihawkHu** [comment]
Hi,
In our experiments, we used _en.m as scripts. With energy normalization, we observed an improvement but honestly we did not investigated too much on it.

**Comment by debottam-dutta7** [comment]
Thanks a lot.
