### ISSUE TITLE
can't find audio file "audio/airport-barcelona-1-87-c.wav"

### ISSUE THREAD

**Issue by NewEricWang** [MihawkHu/DCASE2020_task1#16]
Hi, 
     when running the script "./extr_feat_2020_nodelta_scaled.py" in task1a/3class,  an error is reported: can't find audio file "audio/airport-barcelona-1-87-c.wav".
     I use the input file "evaluation_setup/fold1_train_3class.csv".

    Could you tell me where to find the audio file?

**Comment by MihawkHu** [comment]
Hi,
You can download the dataset via this link https://doi.org/10.5281/zenodo.3819968
The 3-class and 10-class sharethe same audio but only different labels.

**Comment by NewEricWang** [comment]
Thank you! 
In the experiment, I download the dataset via the link: http://dcase.community/challenge2020/task-acoustic-scene-classification#subtask-a
I don't open the link you gave.

**Comment by NewEricWang** [comment]
I have download "TAU-urban-acoustic-scenes-2020-mobile-development", "TAU-urban-acoustic-scenes-2020-mobile-evaluation", "TAU-urban-acoustic-scenes-2020-3class-evaluation" and "TAU-urban-acoustic-scenes-2020-3class-development" from the link http://dcase.community/challenge2020/task-acoustic-scene-classification#subtask-a.
I can't find the audio file "audio/airport-barcelona-1-87-c.wav". 
The dataset (the link https://doi.org/10.5281/zenodo.3819968) already was download.

**Comment by Nilson** [comment]
If I remember correctly, the file might have been removed from the current version of the dataset. Try the first version of the dataset: https://zenodo.org/record/3670167

**Comment by NewEricWang** [comment]
@Nilson , thank you!  After a while, I try it.
