### ISSUE TITLE
algorithm of Lottery Ticket Hypothesis Pruning

### ISSUE THREAD

**Issue by NewEricWang** [MihawkHu/DCASE2020_task1#17]
Hi,
    Do the algorithm of Lottery Ticket Hypothesis Pruning be implemented in the project?

**Comment by MihawkHu** [comment]
Hi, 
Currently the LTH pruning is not included in this repo. We're working on the new version and will release it soon.

**Comment by NewEricWang** [comment]
Good job! Good news!
Eagerly look forward to your new version.
