### ISSUE TITLE
The class label of 10class evaluation data

### ISSUE THREAD

**Issue by NewEricWang** [MihawkHu/DCASE2020_task1#18]
Hi, Hu:
     I have download the dataset via the link you provided. But I can't find the class label of 10class evaluation dataset. 
There is audio file list in "TAU-urban-acoustic-scenes-2020-mobile-evaluation/evaluation_setup/fold1_test.csv".
    Could you send the class labels to me? Thanks!

**Comment by MihawkHu** [comment]
Hi,
Actually we dont have the labels for the test set. The organizer did not release the labels for the test set. You can use the evaluation set (fold1_evaluate.csv) to evaluate your systems.

**Comment by NewEricWang** [comment]
Ok, thanks a lot!
