### ISSUE TITLE
运行时错误

### ISSUE THREAD

**Issue by dwangxxx** [MihawkHu/DCASE2020_task1#2]
作者您好，我在运行这份代码的时候，在训练阶段，有时候会出现StopIteration错误，并且训练的时候，每训练几十个batch就会停顿一会，训练很慢，我想知道您有遇到这种情况吗？
我训练的时候会出现这个warning:
`
/.conda/envs/audio/lib/python3.7/site-packages/keras/utils/data_utils.py:709: UserWarning: An input could not be retrieved. It could be because a worker has died.We do not have any information on the lost sample.
`
我尝试了把batch_size改小或者改大都没用，还有splitted_num改大或改小也没用，我想知道这该怎么解决啊？

**Comment by MihawkHu** [comment]
hello 您好，我们没有出现过StopIteration的错误，会不会有可能是keras或者tensoflow版本的问题。我们用的是keras2.2.4和tensorflow1.12.0。

训练几十个batch就会停顿一会的现象是正常的。受限于内存，我们是每次只load了一部分数据到内存里面，所以会出现训练几十个batch就读另一部分的数据的情况。如果内存足够，可以一次性将数据都读到内存里，训练也会快一点。

这个warning我们也遇到过，没有什么影响，应该可以忽略。

**Comment by dwangxxx** [comment]
> hello 您好，我们没有出现过StopIteration的错误，会不会有可能是keras或者tensoflow版本的问题。我们用的是keras2.2.4和tensorflow1.12.0。
> 
> 训练几十个batch就会停顿一会的现象是正常的。受限于内存，我们是每次只load了一部分数据到内存里面，所以会出现训练几十个batch就读另一部分的数据的情况。如果内存足够，可以一次性将数据都读到内存里，训练也会快一点。
> 
> 这个warning我们也遇到过，没有什么影响，应该可以忽略。

感谢您的回复，尝试一下改变一下keras和tensorflow的版本，这份代码对我们帮助很大，感谢！

**Comment by MihawkHu** [comment]
Thanks!
