### ISSUE TITLE
resnet_layer has no skip connection ?

### ISSUE THREAD

**Issue by julj** [MihawkHu/DCASE2020_task1#3]
Your [resnet_layer](https://github.com/MihawkHu/DCASE2020_task1/blob/master/task1a/10class/fsfcnn/fsfcnn_att.py#L10) has no skip connection, so it looks more like a standard convolutional layer.

**Comment by MihawkHu** [comment]
U r right, the resnet_layer() function u pointed out is not an exact resnet layer. The skip connection is implemented in https://github.com/MihawkHu/DCASE2020_task1/blob/master/task1a/10class/resnet/resnet.py#L95.

**Comment by huckiyang** [comment]
@julj Yes, we separate the skip connection inside the resnet_model() as @MihawkHu said. Thanks.
