### ISSUE TITLE
I'm confused of file directory.

### ISSUE THREAD

**Issue by jiminbot20** [MihawkHu/DCASE2020_task1#4]
I'm trying to run your code, but I'm confused of composing data.
1. Where does folder 'data_2020' belong? what's the upper directory?
2. Where should I unzip original data given by DCASE?

**Comment by MihawkHu** [comment]
Thanks for your interests. For your questions:
  1. 'data_2020' indicates the data folder. It should contain audio files. If you look into the original data set, u can easily get it.
  2. You can find it in DCASE official website http://dcase.community/challenge2020/task-acoustic-scene-classification .

**Comment by jiminbot20** [comment]
Thank you for reply, here is supplemented questions.
1. The intention of the question was that hierarchy of the folder. Is _DCASE2020_task1/task1a/data_augmentation/audio_based/data_2020_ correct hierarchy? 
2. As an extension of the first question, Is unzipping **TAU-urban-acoustic-scenes-2020-mobile-development.audio.*.zip(1~16)** to following directory _DCASE2020_task1/task1a/data_augmentation/audio_based/data_2020/audio_ right?

**Comment by MihawkHu** [comment]
Hi, I think the folder hierarchy does not matter so much. You need to assign the correct data directory to each position in the codes. I would suggest to use 'DCASE2020_task1/task1a/data_2020/'.

**Comment by jiminbot20** [comment]
thank you for your kindness
