### ISSUE TITLE
I confused the Accuracy on Evaluation dataset in Technical Report ?

### ISSUE THREAD

**Issue by OrangeBaoWang** [MihawkHu/DCASE2020_task1#5]
I download the Evaluation dataset from   https://doi.org/10.5281/zenodo.3685835
but  I found the dataset has no label information. How to calculate the Accuracy on Evaluation dataset  ?

![image](https://user-images.githubusercontent.com/44084330/104982421-98ef6080-5a45-11eb-9ac6-dbe27a2d5b86.png)

**Comment by MihawkHu** [comment]
Hi, thanks for your interests. For your questions, the challenge organizer does not provide the labels for evaluation dataset. If you want to evaluate your system, you can use the evaluation audios in development dataset.
