### ISSUE TITLE
Is 'fold1_train_full.csv' has to change into 'fold1_trainall_full.csv' or 'fold1_train_all.csv' ?

### ISSUE THREAD

**Issue by jiminbot20** [MihawkHu/DCASE2020_task1#6]
https://github.com/MihawkHu/DCASE2020_task1/blob/44187eb3c882c8c82ea0721145cbb9ea624a3b4e/task1a/10class/fcnn/train_fcnn.py#L29

There is no such exact filename matching with 'fold1_train_full.csv'
![image](https://user-images.githubusercontent.com/63258184/105011510-62830700-5a80-11eb-85fb-6277be0293ba.png)

Is 'fold1_train_full.csv' has to change into 'fold1_trainall_full.csv' or 'fold1_train_all.csv' ?

**Comment by MihawkHu** [comment]
Hi, thanks for your interests. Yes it depends how your training csv file is named. You can change it to the real file name u are using.

**Comment by jiminbot20** [comment]
Thanks a lot!

**Comment by Noumanijaz744** [comment]
Hi your reply will be really helpful for me.
for implementing task1a 3class the evaluation setup contain audio labels from other devices also but the official datasets evaluation setup only contain the audio files of device A ?can you please guide me i have extracted 128 logmel features for 3class development datasets .
i will be really thankful of your greatness to reply me and guide accordingly to run your code
