### ISSUE TITLE
little typo

### ISSUE THREAD

**Issue by jiminbot20** [MihawkHu/DCASE2020_task1#7]
https://github.com/MihawkHu/DCASE2020_task1/blob/19000af24f62d37e034333b206793935bad13d94/task1a/3class/fcnn/fcnn_att.py#L6

'channel_attentionn' need to change into 'channel_attention'

double n :)

**Comment by MihawkHu** [comment]
Thanks for pointing it out. We have fixed it.

**Comment by jiminbot20** [comment]
welcome
