### ISSUE TITLE
Augmentation problems

### ISSUE THREAD

**Issue by jiminbot20** [MihawkHu/DCASE2020_task1#8]
Questions for running add, noise, pitch, time augmentation, 
DCASE2020_task1/task1a/data_augmentation/audio_based/

1. Should all development data be augmented? It confuses because there are no such directory(_csv_file = 'evaluation_setup/fold1_train.csv'_ in line 16, gen_extr_feat_2020_add.py). Furthermore, provided csv files in _task1a/data_augmentation/audio_based/fold1_train_add.csv_ contains only device A data. so I'm confusing.
2. If all development data should be augmented, using _'task1a/10class/evaluation_setup/fold1_trainall_full.csv'_ is fine?
3. Is it possible to run _10class/fcnn/train_fcnn.py_ without augmentation? If it could, could you teach me how to?

**Comment by MihawkHu** [comment]
Hi, we thank you very much for your interests. For ur questions:
1. As stated in our paper and codes, all training data, totally 13965 utts, are used for data augmentation. The provided csv files contain data from all devices, not only device A.
2. After augmentating, using 'task1a/10class/evaluation_setup/fold1_trainall_full.csv' to train the whole system is fine. Please make sure that ur training csv contains all augmented data u generated. 
3. It's ok to run fcnn model without augmented data. We just added the instructions, as shown in line 27-28 of 10class/fcnn/train_fcnn.py, u can use  'evaluation_setup/fold1_train.csv' and delete all the aug_csv parts. Then it's to run fcnn on original training data, totally 13965 utts. However, please note that, fcnn is a data-hungry model. It did not perform well in our experiments when data augmentation is not used.

**Comment by jiminbot20** [comment]
Thank you I will keep working on

**Comment by jiminbot20** [comment]
Thank for your help, I successfully run without augmentation and got 0.7047 evaluation accuracy.
By the way, is it right to augment evaluation data not just train data?

**Comment by MihawkHu** [comment]
For your questions, it's not right to augment evaluation data.

**Comment by huckiyang** [comment]
@jiminbot20 It is incorrect to augment the evaluation data if you would like to publish a scientific paper. 
In that case, the augmented result will indicate an unfair performance study from a general machine experiment setup.

**Comment by jiminbot20** [comment]
Thank you I miss understood. So, to be clear, Is the **'fold1_train'** only file corresponding to augmentation?

**Comment by MihawkHu** [comment]
'fold1_train' is from the file name of the original data set, in which 'fold1' indicates a train-test splitting way. It's not related to the data augmentation. For augmented data, please make sure that your train csv file contains all data u want to used for training.

**Comment by jiminbot20** [comment]
Got it. It seems like I need to look into the codes a little deeper. Thank you for your kindness

**Comment by jiminbot20** [comment]
Got it. It seems like I need to look into the codes a little deeper. Thank you for your kindness
