### ISSUE TITLE
problem of pretrained models 

### ISSUE THREAD

**Issue by OrangeBaoWang** [MihawkHu/DCASE2020_task1#9]
I tested the pretrained models ,such as mob2-all.h5 or mobnet-model-0.9517.hdf5. using  mobile  device recording data with very low accuracy. Why ?  Were the train data set included augment data when training these models ?

**Comment by huckiyang** [comment]
@OrangeBaoWang hello, it looks like you are using mob2, which is a pretrained model for task-1b (3 classes).
which dataset you were testing when facing this condition? (e.g., 1-a or 1-b) - since 1-a data actually has 10 classes, which is different from task-1b.

**Comment by OrangeBaoWang** [comment]
The test dataset is recorded by myself using mobile device.Any way, Were the train data set included augment data when training mob2 models ?

**Comment by huckiyang** [comment]
@OrangeBaoWang The acoustic classification task is often device and label-depend. It is hard to justify the transferability over different datasets. For the provided mobile-net trained on task 1-b, please refer to the details in section 5.4 of our DECASE paper. 
https://arxiv.org/pdf/2007.08389.pdf - thanks.
